### PR TITLE
chore: add project boilerplate from template

### PR DESCRIPTION
**Pull request by pushkarm029**
## Summary by Sourcery

Initialize the 'cloud_telemetry' project using a cookiecutter template, setting up the project structure, documentation, CI/CD workflows, and initial test framework. This includes adding a README, Makefile, GitHub Actions for CI, and configuration files for documentation and code quality tools.

New Features:
- Introduce a new Python package 'cloud_telemetry' with an entry point script that prints a welcome message.

Enhancements:
- Add a comprehensive README.md file with sections on usage, installation, development, contributing, code of conduct, versioning, license, and contact information.
- Include a Makefile to streamline development tasks such as creating virtual environments, installing dependencies, running tests, and generating documentation.

Build:
- Add a .readthedocs.yaml configuration file to set up Read the Docs for building project documentation.
- Include a .markdownlint.yaml configuration file to enforce markdown style guidelines.

CI:
- Set up GitHub Actions workflows for code quality checks, PR validation, code testing, documentation checks, and vulnerability testing.
- Add a custom GitHub Action to set up Python and Poetry environments.

Deployment:
- Add a GitHub Actions workflow to automate the release of the package to PyPI upon new releases.

Documentation:
- Add Sphinx configuration and Makefile for generating project documentation.
- Include a PULL_REQUEST_TEMPLATE.md to guide contributors in creating pull requests.

Tests:
- Add unit and integration test directories with initial test files to verify the existence of the __init__.py file.

Chores:
- Add a .cruft.json file to track the template used for project initialization.
- Include a .pre-commit-config.yaml file to set up pre-commit hooks for code quality checks.

### CODE REVIEW

**Comment by pushkarm029** [comment]
some tests fail because the `codecov` token is not yet provided.

**Review by uniqueg — COMMENTED** [review]
You should probably upgrade to the latest version of the Cookiecutter - and _after_ https://github.com/elixir-cloud-aai/cookiecutter-python/pull/14 has been merged (hopefully today/tomorrow).

Another possible concern is that it is not entirely clear to me yet what the code will look like. Does it make sense to distribute it as a package on PyPI (my guess is yes)? Can you foresee any use for a console script included in the project, i.e., some CLI client (my guess is no)?

Depending on these, perhaps some of the generated content should be adjusted (e.g., the console script section removed from `pyproject.toml`, the `release_pypi.yaml` workflow removed etc).

Other than that, I think it's good to go.

So please update Cruft once the Cookiecutter PR is merged, then please have another look at the generated content and check if there's anything that you think may not fit your project. In case you are unsure, just leave it - we can always change things later on. When you are done with that, please ask for a re-review and I will approve.

**Comment by uniqueg** [comment]
> some tests fail because the `codecov` token is not yet provided.

I have added `CODECOV_TOKEN` as a repo secret

**Review by uniqueg — APPROVED** [review]

**Comment by uniqueg** [comment]
@Pushkarm029: Please fix the linting and doc check issues.

@JaeAeich: Maybe you can help with the doc check one?

**Comment by JaeAeich** [comment]
@Pushkarm029 you haven't generated the docs, please do so by running `make d` in root dir and that should fix the CI.

For linting you could either manually add fullstop in the pydoc of init.py file, or wait for [#15](https://github.com/elixir-cloud-aai/cookiecutter-python/pull/15) to merge and run `make u` in root dir and that should fix it autmatically.

**Comment by JaeAeich** [comment]
> For linting you could either manually add fullstop in the pydoc of init.py file, or wait for [#15](https://github.com/elixir-cloud-aai/cookiecutter-python/pull/15) to merge and run `make u` in root dir and that should fix it autmatically.

Cookiecutter template has been updated, running `make u` should fix the issue that prropogate from template. If not then its this repo's issue, use `make fl` to fix those.

**Comment by pushkarm029** [comment]
CI green now @JaeAeich @uniqueg

**Comment by pushkarm029** [comment]
I updated the cookiecutter by directly creating a new one. because on using `make u`, I am getting this error, maybe some typo: ~~cruff~~ cruft
```py
(.venv) pushkarm029@thinkpad:~/cloud-telemetry(cookie-cutter⚡) » make u 

Updating the template +++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Using latest version from remote: https://github.com/elixir-cloud-aai/cookiecutter-python.
Command not found: cruff
make: *** [Makefile:118: update] Error 1

```

**Comment by JaeAeich** [comment]
> I updated the cookiecutter by directly creating a new one. because on using `make u`, I am getting this error, maybe some typo: ~cruff~ cruft
> 
> ```python
> (.venv) pushkarm029@thinkpad:~/cloud-telemetry(cookie-cutter⚡) » make u 
> 
> Updating the template +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> 
> Using latest version from remote: https://github.com/elixir-cloud-aai/cookiecutter-python.
> Command not found: cruff
> make: *** [Makefile:118: update] Error 1
> ```

yeah, should be fixed in [#16](https://github.com/elixir-cloud-aai/cookiecutter-python/pull/16), idk how that got slipped in,  if you find any more such issues, please report in the issues sections :).

**Comment by pushkarm029** [comment]
Yeah, why not @JaeAeich, let us merge this then

**Comment by pushkarm029** [comment]
@uniqueg, could you approve this again to merge?

**Review by uniqueg — APPROVED** [review]

**Pull request merged**
